/*
 * generated by Xtext 2.12.0
 */
package com.softtek


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Rdl2RuntimeModule extends AbstractRdl2RuntimeModule {
}
