/*
 * generated by Xtext 2.12.0
 */
package com.softtek


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Rdl2StandaloneSetup extends Rdl2StandaloneSetupGenerated {

	def static void doSetup() {
		new Rdl2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
